# Generated by Django 5.2.1 on 2025-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='category_courses', to='course_app.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_lan',
            field=models.CharField(max_length=32, verbose_name='Язык курса: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_lan_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Язык курса: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_lan_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Язык курса: '),
        ),
    ]
